/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as AuthenticatedVeilleRouteImport } from './routes/_authenticated/veille'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedRecommandationsRouteImport } from './routes/_authenticated/recommandations'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAnalyserRouteImport } from './routes/_authenticated/analyser'
import { Route as AuthenticatedPatrimoineIndexRouteImport } from './routes/_authenticated/patrimoine.index'
import { Route as AuthenticatedPatrimoineNouveauRouteImport } from './routes/_authenticated/patrimoine.nouveau'
import { Route as AuthenticatedPatrimoineIdRouteImport } from './routes/_authenticated/patrimoine.$id'
import { Route as AuthenticatedAnalyseIdRouteImport } from './routes/_authenticated/analyse.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksRefreshMarketDataRouteImport } from './routes/api/public/hooks/refresh-market-data'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVeilleRoute = AuthenticatedVeilleRouteImport.update({
  id: '/veille',
  path: '/veille',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommandationsRoute =
  AuthenticatedRecommandationsRouteImport.update({
    id: '/recommandations',
    path: '/recommandations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyserRoute = AuthenticatedAnalyserRouteImport.update({
  id: '/analyser',
  path: '/analyser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatrimoineIndexRoute =
  AuthenticatedPatrimoineIndexRouteImport.update({
    id: '/patrimoine/',
    path: '/patrimoine/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatrimoineNouveauRoute =
  AuthenticatedPatrimoineNouveauRouteImport.update({
    id: '/patrimoine/nouveau',
    path: '/patrimoine/nouveau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatrimoineIdRoute =
  AuthenticatedPatrimoineIdRouteImport.update({
    id: '/patrimoine/$id',
    path: '/patrimoine/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyseIdRoute = AuthenticatedAnalyseIdRouteImport.update({
  id: '/analyse/$id',
  path: '/analyse/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshMarketDataRoute =
  ApiPublicHooksRefreshMarketDataRouteImport.update({
    id: '/api/public/hooks/refresh-market-data',
    path: '/api/public/hooks/refresh-market-data',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analyser': typeof AuthenticatedAnalyserRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/recommandations': typeof AuthenticatedRecommandationsRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/veille': typeof AuthenticatedVeilleRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/analyse/$id': typeof AuthenticatedAnalyseIdRoute
  '/patrimoine/$id': typeof AuthenticatedPatrimoineIdRoute
  '/patrimoine/nouveau': typeof AuthenticatedPatrimoineNouveauRoute
  '/patrimoine/': typeof AuthenticatedPatrimoineIndexRoute
  '/api/public/hooks/refresh-market-data': typeof ApiPublicHooksRefreshMarketDataRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analyser': typeof AuthenticatedAnalyserRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/recommandations': typeof AuthenticatedRecommandationsRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/veille': typeof AuthenticatedVeilleRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/analyse/$id': typeof AuthenticatedAnalyseIdRoute
  '/patrimoine/$id': typeof AuthenticatedPatrimoineIdRoute
  '/patrimoine/nouveau': typeof AuthenticatedPatrimoineNouveauRoute
  '/patrimoine': typeof AuthenticatedPatrimoineIndexRoute
  '/api/public/hooks/refresh-market-data': typeof ApiPublicHooksRefreshMarketDataRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analyser': typeof AuthenticatedAnalyserRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/recommandations': typeof AuthenticatedRecommandationsRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/veille': typeof AuthenticatedVeilleRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/_authenticated/analyse/$id': typeof AuthenticatedAnalyseIdRoute
  '/_authenticated/patrimoine/$id': typeof AuthenticatedPatrimoineIdRoute
  '/_authenticated/patrimoine/nouveau': typeof AuthenticatedPatrimoineNouveauRoute
  '/_authenticated/patrimoine/': typeof AuthenticatedPatrimoineIndexRoute
  '/api/public/hooks/refresh-market-data': typeof ApiPublicHooksRefreshMarketDataRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analyser'
    | '/assistant'
    | '/compte'
    | '/dashboard'
    | '/historique'
    | '/radar'
    | '/recommandations'
    | '/upgrade'
    | '/veille'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/analyse/$id'
    | '/patrimoine/$id'
    | '/patrimoine/nouveau'
    | '/patrimoine/'
    | '/api/public/hooks/refresh-market-data'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analyser'
    | '/assistant'
    | '/compte'
    | '/dashboard'
    | '/historique'
    | '/radar'
    | '/recommandations'
    | '/upgrade'
    | '/veille'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/analyse/$id'
    | '/patrimoine/$id'
    | '/patrimoine/nouveau'
    | '/patrimoine'
    | '/api/public/hooks/refresh-market-data'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analyser'
    | '/_authenticated/assistant'
    | '/_authenticated/compte'
    | '/_authenticated/dashboard'
    | '/_authenticated/historique'
    | '/_authenticated/radar'
    | '/_authenticated/recommandations'
    | '/_authenticated/upgrade'
    | '/_authenticated/veille'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/_authenticated/analyse/$id'
    | '/_authenticated/patrimoine/$id'
    | '/_authenticated/patrimoine/nouveau'
    | '/_authenticated/patrimoine/'
    | '/api/public/hooks/refresh-market-data'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  ApiPublicHooksRefreshMarketDataRoute: typeof ApiPublicHooksRefreshMarketDataRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/veille': {
      id: '/_authenticated/veille'
      path: '/veille'
      fullPath: '/veille'
      preLoaderRoute: typeof AuthenticatedVeilleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommandations': {
      id: '/_authenticated/recommandations'
      path: '/recommandations'
      fullPath: '/recommandations'
      preLoaderRoute: typeof AuthenticatedRecommandationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyser': {
      id: '/_authenticated/analyser'
      path: '/analyser'
      fullPath: '/analyser'
      preLoaderRoute: typeof AuthenticatedAnalyserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrimoine/': {
      id: '/_authenticated/patrimoine/'
      path: '/patrimoine'
      fullPath: '/patrimoine/'
      preLoaderRoute: typeof AuthenticatedPatrimoineIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrimoine/nouveau': {
      id: '/_authenticated/patrimoine/nouveau'
      path: '/patrimoine/nouveau'
      fullPath: '/patrimoine/nouveau'
      preLoaderRoute: typeof AuthenticatedPatrimoineNouveauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrimoine/$id': {
      id: '/_authenticated/patrimoine/$id'
      path: '/patrimoine/$id'
      fullPath: '/patrimoine/$id'
      preLoaderRoute: typeof AuthenticatedPatrimoineIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyse/$id': {
      id: '/_authenticated/analyse/$id'
      path: '/analyse/$id'
      fullPath: '/analyse/$id'
      preLoaderRoute: typeof AuthenticatedAnalyseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-market-data': {
      id: '/api/public/hooks/refresh-market-data'
      path: '/api/public/hooks/refresh-market-data'
      fullPath: '/api/public/hooks/refresh-market-data'
      preLoaderRoute: typeof ApiPublicHooksRefreshMarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyserRoute: typeof AuthenticatedAnalyserRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedRecommandationsRoute: typeof AuthenticatedRecommandationsRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedVeilleRoute: typeof AuthenticatedVeilleRoute
  AuthenticatedAnalyseIdRoute: typeof AuthenticatedAnalyseIdRoute
  AuthenticatedPatrimoineIdRoute: typeof AuthenticatedPatrimoineIdRoute
  AuthenticatedPatrimoineNouveauRoute: typeof AuthenticatedPatrimoineNouveauRoute
  AuthenticatedPatrimoineIndexRoute: typeof AuthenticatedPatrimoineIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyserRoute: AuthenticatedAnalyserRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedRecommandationsRoute: AuthenticatedRecommandationsRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedVeilleRoute: AuthenticatedVeilleRoute,
  AuthenticatedAnalyseIdRoute: AuthenticatedAnalyseIdRoute,
  AuthenticatedPatrimoineIdRoute: AuthenticatedPatrimoineIdRoute,
  AuthenticatedPatrimoineNouveauRoute: AuthenticatedPatrimoineNouveauRoute,
  AuthenticatedPatrimoineIndexRoute: AuthenticatedPatrimoineIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalCguRoute: LegalCguRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  ApiPublicHooksRefreshMarketDataRoute: ApiPublicHooksRefreshMarketDataRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
